<?php
declare(strict_types=1);

// AmneziaWarp SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

AmneziaWarpUtility::setRegistrar(function (AmneziaWarpUtility $u): void {
    $u->clean = [AmneziaWarpClean::class, 'call'];
    $u->done = [AmneziaWarpDone::class, 'call'];
    $u->make_error = [AmneziaWarpMakeError::class, 'call'];
    $u->feature_add = [AmneziaWarpFeatureAdd::class, 'call'];
    $u->feature_hook = [AmneziaWarpFeatureHook::class, 'call'];
    $u->feature_init = [AmneziaWarpFeatureInit::class, 'call'];
    $u->fetcher = [AmneziaWarpFetcher::class, 'call'];
    $u->make_fetch_def = [AmneziaWarpMakeFetchDef::class, 'call'];
    $u->make_context = [AmneziaWarpMakeContext::class, 'call'];
    $u->make_options = [AmneziaWarpMakeOptions::class, 'call'];
    $u->make_request = [AmneziaWarpMakeRequest::class, 'call'];
    $u->make_response = [AmneziaWarpMakeResponse::class, 'call'];
    $u->make_result = [AmneziaWarpMakeResult::class, 'call'];
    $u->make_point = [AmneziaWarpMakePoint::class, 'call'];
    $u->make_spec = [AmneziaWarpMakeSpec::class, 'call'];
    $u->make_url = [AmneziaWarpMakeUrl::class, 'call'];
    $u->param = [AmneziaWarpParam::class, 'call'];
    $u->prepare_auth = [AmneziaWarpPrepareAuth::class, 'call'];
    $u->prepare_body = [AmneziaWarpPrepareBody::class, 'call'];
    $u->prepare_headers = [AmneziaWarpPrepareHeaders::class, 'call'];
    $u->prepare_method = [AmneziaWarpPrepareMethod::class, 'call'];
    $u->prepare_params = [AmneziaWarpPrepareParams::class, 'call'];
    $u->prepare_path = [AmneziaWarpPreparePath::class, 'call'];
    $u->prepare_query = [AmneziaWarpPrepareQuery::class, 'call'];
    $u->graphql_body = [AmneziaWarpGraphql::class, 'body'];
    $u->graphql_errors = [AmneziaWarpGraphql::class, 'errors'];
    $u->result_basic = [AmneziaWarpResultBasic::class, 'call'];
    $u->result_body = [AmneziaWarpResultBody::class, 'call'];
    $u->result_headers = [AmneziaWarpResultHeaders::class, 'call'];
    $u->transform_request = [AmneziaWarpTransformRequest::class, 'call'];
    $u->transform_response = [AmneziaWarpTransformResponse::class, 'call'];
});
